apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - storage-pvc.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - ingress.yaml
  - hpa-web.yaml
