apiVersion: v1
kind: Service
metadata:
  name: whatsapp-api-svc
  namespace: __K8S_NAMESPACE__
spec:
  type: ClusterIP
  selector:
    app: whatsapp-api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-web-svc
  namespace: __K8S_NAMESPACE__
spec:
  type: ClusterIP
  selector:
    app: whatsapp-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
