apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-ksa
  namespace: __K8S_NAMESPACE__
  annotations:
    iam.gke.io/gcp-service-account: __GSA_API__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-ksa
  namespace: __K8S_NAMESPACE__
  annotations:
    iam.gke.io/gcp-service-account: __GSA_WEB__
