apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  namespace: __K8S_NAMESPACE__
type: Opaque
stringData:
  NEXTAUTH_URL: "https://__DOMAIN__"
  NEXTAUTH_SECRET: "replace_with_strong_secret"
  API_BASE_URL: "https://__DOMAIN__/api/v1"
  NEXT_PUBLIC_API_BASE_URL: "https://__DOMAIN__/api/v1"
